name: Xweed
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">2.2.2 <3.0.0"

dependencies:
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.5
  google_sign_in: ^4.5.1
  flutter_blue: ^0.7.2
  splashscreen: ^1.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  provider: ^4.1.3
  get_it: ^4.0.2
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
